### ISSUE TITLE
Looper documentation TODO list

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#513]
Just keeping for myself a list of TODO things for looper docs update:

- [ ] Howto: Run looper from PEPhub
- [ ] Combine 'Browsable HTML Reports' and 'Using pipestat'
- [ ] Combine 'Concentric templates' with 'Looper variable namespaces' -- These are also related to "Running on a cluster with divvy" -- I need to explain the adapters, which goes along with the looper variable namespaces
- [ ] "Pipeline tiers" probably belongs under "Running a pipeline", which should explain the difference between `looper run` and `looper runp`.
- [ ] "Defining loper config" probably should come *after* "Defining a project".
